export const images = [
  { id: 1, src: "/images/food_1.jpg", alt: "Food 1" },
  { id: 2, src: "/images/food_2.jpg", alt: "Food 2" },
  { id: 3, src: "/images/food_3.jpg", alt: "Food 3" },
  { id: 4, src: "/images/food_4.jpg", alt: "Food 4" },
  { id: 5, src: "/images/food_5.jpg", alt: "Food 5" },
  { id: 6, src: "/images/food_6.jpg", alt: "Food 6" },
  { id: 7, src: "/images/food_7.jpg", alt: "Food 7" },
  { id: 8, src: "/images/food_8.jpg", alt: "Food 8" },
  { id: 9, src: "/images/food_9.jpg", alt: "Food 9" },
  { id: 10, src: "/images/food_10.jpg", alt: "Food 10" },
  { id: 11, src: "/images/food_11.jpg", alt: "Food 11" },
  { id: 12, src: "/images/food_12.jpg", alt: "Food 12" },
  { id: 13, src: "/images/food_13.jpg", alt: "Food 13" },
  { id: 14, src: "/images/food_14.jpg", alt: "Food 14" },
  { id: 15, src: "/images/food_15.jpg", alt: "Food 15" },
  { id: 16, src: "/images/food_16.jpg", alt: "Food 16" },
  { id: 17, src: "/images/food_17.jpg", alt: "Food 17" },
  { id: 6, src: "/images/food_6.jpg", alt: "Food 6" },
];
export const restaurant = [
  {
    id: 1,
    src: "/images/rest_1.jpg",
    offer: "Items at ₹179",
    title: "Delicious Pizza",
    rating: 4.2,
    minTime: 30,
    maxTime: 40,
    name: "Pizzas",
    place: "MG Road",
  },
  {
    id: 2,
    src: "/images/rest_2.jpg",
    offer: "20% off on all items",
    title: "Spicy Indian Cuisine",
    rating: 4.5,
    minTime: 25,
    maxTime: 35,
    name: "Indian",
    place: "Brigade Road",
  },
  {
    id: 3,
    src: "/images/rest_3.jpg",
    offer: "Free Dessert on orders above ₹500",
    title: "Chinese Delight",
    rating: 4.1,
    minTime: 20,
    maxTime: 30,
    name: "Chinese",
    place: "Koramangala",
  },
  {
    id: 4,
    src: "/images/rest_4.jpg",
    offer: "Buy 1 Get 1 Free",
    title: "Burger Haven",
    rating: 4.3,
    minTime: 15,
    maxTime: 25,
    name: "Burgers",
    place: "Indiranagar",
  },
  {
    id: 5,
    src: "/images/rest_5.jpg",
    offer: "Flat ₹100 off on first order",
    title: "Sushi World",
    rating: 4.7,
    minTime: 35,
    maxTime: 45,
    name: "Sushi",
    place: "Whitefield",
  },
  {
    id: 6,
    src: "/images/rest_6.jpg",
    offer: "25% off on all items",
    title: "Italian Pasta",
    rating: 4.6,
    minTime: 30,
    maxTime: 40,
    name: "Italian",
    place: "Jayanagar",
  },
  {
    id: 7,
    src: "/images/rest_7.jpg",
    offer: "20% off on orders above ₹300",
    title: "Mexican Fiesta",
    rating: 4.2,
    minTime: 20,
    maxTime: 30,
    name: "Mexican",
    place: "Electronic City",
  },
  {
    id: 8,
    src: "/images/rest_8.jpg",
    offer: "Free Delivery on orders above ₹200",
    title: "Healthy Salads",
    rating: 4.4,
    minTime: 15,
    maxTime: 20,
    name: "Salads",
    place: "HSR Layout",
  },
  {
    id: 9,
    src: "/images/rest_9.jpg",
    offer: "10% off on all items",
    title: "Tasty Thai",
    rating: 4.0,
    minTime: 25,
    maxTime: 35,
    name: "Thai",
    place: "Bellandur",
  },
  {
    id: 10,
    src: "/images/rest_10.jpg",
    offer: "Free Drink with every order",
    title: "American Diner",
    rating: 4.3,
    minTime: 30,
    maxTime: 40,
    name: "American",
    place: "Marathahalli",
  },
  {
    id: 11,
    src: "/images/rest_11.jpg",
    offer: "15% off on all items",
    title: "BBQ Corner",
    rating: 4.5,
    minTime: 35,
    maxTime: 45,
    name: "BBQ",
    place: "Yelahanka",
  },
  {
    id: 12,
    src: "/images/rest_12.jpg",
    offer: "Buy 2 Get 1 Free",
    title: "Dessert Delights",
    rating: 4.8,
    minTime: 20,
    maxTime: 30,
    name: "Desserts",
    place: "Sarjapur",
  },
];
